[DEFAULT]
debug = false
smtp_server = localhost
error_email_from = paste@localhost
CKAN_DB_HOST = db
CKAN_DB_PORT = 5432
CKAN_DB_PASSWORD = ckan
CKAN_DATASTORE_DB_PASSWORD = ckan_datastore
CKAN_DATASTORE_READONLY_PASSWORD = ckan_datastore_ro

[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000

[app:main]
use = config:/srv/app/src/ckan/test-core.ini

## ckan-docker image sets site_url to localhost:5000. Domain must reflect URL's
## value or else session data will not persist through requests and tests for
## flash messages will fail
ckan.site_url = http://localhost:5000
SESSION_COOKIE_DOMAIN = localhost

# Insert any custom config settings to be used when running your extension's
# tests here.
ckan.plugins = pages image_view

ckanext.pages.organization = True
ckanext.pages.group = True

sqlalchemy.url = postgresql://ckan:%(CKAN_DB_PASSWORD)s@%(CKAN_DB_HOST)s:%(CKAN_DB_PORT)s/ckan_test
ckan.datastore.write_url = postgresql://ckan_datastore:%(CKAN_DATASTORE_DB_PASSWORD)s@%(CKAN_DB_HOST)s:%(CKAN_DB_PORT)s/datastore_test
ckan.datastore.read_url = postgresql://ckan_datastore_ro:%(CKAN_DATASTORE_READONLY_PASSWORD)s@%(CKAN_DB_HOST)s:%(CKAN_DB_PORT)s/datastore_test

[loggers]
keys = root, ckan, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_ckan]
qualname = ckan
handlers =
level = INFO

[logger_sqlalchemy]
handlers =
qualname = sqlalchemy.engine
level = WARN

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
